### ISSUE TITLE
Question: With ic-nix, how should I execute my ic-repl scripts?

### ISSUE THREAD

**Issue by saikatdas0790** [ninegua/ic-nix#37]
Hi @ninegua 

With ic-nix, how should I execute my ic-repl tests that are saved as .sh files?

Previously I had them saved like this
![image](https://user-images.githubusercontent.com/7412443/215268875-d4d1d9af-530c-4c1f-b83f-32a916e465b3.png)
in a `.sh` file

And I just made them executable and run them like bash scripts. But now, my ic-repl binary lives inside the nix-store. 
![image](https://user-images.githubusercontent.com/7412443/215269313-c9e6370e-f1e0-40b8-babf-b0efe65c0484.png)

Should I hard code that value? Is there a way to dynamically reference it using `which ic-repl`?

**Comment by saikatdas0790** [comment]
Found a workaround. Instead of embedding the execution binary at the top of the script, I'm specifying the binary from the callsite. Would have liked to figure out this answer though

**Comment by ninegua** [comment]
The recommended solution to this problem is to create the shell script through nix. Here is an example to get started https://nixos.wiki/wiki/Shell_Scripts, but the gist is that:

1. You run nix-build to install a shell script.
2. The shell script is created from `writeShellScript` in a nix file.
3. The nix expression could reference `ic-repl` from nix packages.
4. The resulting script created by `nix-build` would have the proper and complete path to the right `ic-repl`.
